Layout/EmptyLinesAroundBeginBody:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/LineLength:
  Max: 120
Style/StringLiterals:
  EnforcedStyle: double_quotes
